version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: json
    versions:
    - "> 2.1.0"
  - dependency-name: json
    versions:
    - "> 2.2.0"
  - dependency-name: json
    versions:
    - ">= 2.3.a, < 2.4"
